name: Build and Publish Docker Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    tags: [ 'v*.*.*' ]
    branches:
      - "dev"
      - "docker"
      - "master"

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: "docker.io"
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_INSTANCE: ${{ secrets.GCP_INSTANCE }}
  GCP_SSH_USERNAME: ${{ secrets.GCP_SSH_USERNAME }}
  GCP_SSH_PASSWORD: ${{ secrets.GCP_SSH_PASSWORD }}
  GCP_SSH_COMMAND: ${{ vars.GCP_SSH_COMMAND }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'

      # Clone my_api
      - name: Clone my_api
        run: |
          mkdir ../my_api
          git clone https://${{ secrets.MYAPI_GIT }} ../my_api

      # Install flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0

      # Install project's dependencies
      - name: Install dependencies
        run: |
          flutter pub get

      # Generate locales
      - name: Generate locales
        run: |
          dart run easy_localization:generate -S assets/locale -f keys -o locale_keys.g.dart

      # Generate icons if dev
      - name: Generate DEV icons
        if: ${{ github.ref_name == 'dev' }}
        run: |
          dart run flutter_launcher_icons -v -f flutter_launcher_icons_dev.yaml
      
      # Build web
      - name: Build web
        run: |
          flutter build web --release --web-renderer canvaskit --no-tree-shake-icons

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ env.GCP_SA_KEY }}'
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Pull and Up docker container in GCP
        run: gcloud compute ssh ${{ env.GCP_SSH_USERNAME }}@${{ env.GCP_INSTANCE }} --zone=us-west1-a --command="${{ env.GCP_SSH_COMMAND }}"
